server:
  port: 8080
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: chatroom
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: chatapp
      port: 27017
      host: localhost
      uri: mongodb://localhost:27017/qadr
aws:
  s3:
    access-key: AKIA2K65PJYBFLDDTZ2H
    secret-key: 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
    bucket-name: "spring-chat-room"
    bucket-region: "us-east-1"
