server:
  port:
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  application:
    name: chatroom
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      database: chatapp
      uri: mongodb://localhost:27017

